const teacherProfiles={};
    const chats={};
    let selectedTeacher=null;let hintTimer;
    function isArabic(){return document.documentElement.lang==="ar"}
    function showProfile(id){const profile=teacherProfiles[id],panel=document.getElementById("profilePanel"),ar=document.documentElement.lang==="ar",subject=ar?profile.subjectAr:profile.subject,location=ar?profile.locationAr:profile.location,helps=ar?profile.helpsAr:profile.helps,style=ar?profile.styleAr:profile.style;panel.innerHTML=`<button class="profile-close" aria-label="Close profile" onclick="closeProfile()">×</button><div class="profile-grid"><div><div class="avatar ${profile.color}">${profile.initials}</div><h3>${profile.name}</h3><p>${subject}</p><span class="badge">✓ ${ar?"تم التحقق من المؤهلات":"Verified qualifications"}</span></div><div><div class="profile-list"><div class="profile-point"><b>${ar?"ما الذي يمكن أن يساعدك فيه هذا المدرس":"What this teacher can help with"}</b><span>${helps}</span></div><div class="profile-point"><b>${ar?"أسلوب التدريس ودعم الطالب":"Teaching style and student support"}</b><span>${style}</span></div><div class="profile-point"><b>${ar?"تفاصيل الدرس":"Lesson details"}</b><span>${location} · ${profile.price} · ★ ${profile.rating}</span></div></div><div style="margin-top:14px"><button class="primary" onclick="openChat('${id}')">${ar?"راسل المدرس بشكل خاص ←":"Message "+profile.name.replace("Ms. ","").replace("Dr. ","")+" privately →"}</button></div></div></div>`;panel.classList.add("show");panel.scrollIntoView({behavior:"smooth",block:"nearest"})}
    function closeProfile(){document.getElementById("profilePanel").classList.remove("show")}
    function filterTeachers(button){Array.from(document.querySelectorAll(".filter")).forEach(item=>item.classList.remove("active"));button.classList.add("active");const requested=button.dataset.subject;let shown=0;Array.from(document.querySelectorAll(".teacher")).forEach(card=>{const match=requested==="all"||card.dataset.subject===requested;card.style.display=match?"block":"none";if(match)shown++});document.getElementById("resultText").textContent=isArabic()?`يتم عرض ${shown} مدرس${shown===1?"":"ين"} موثوقين.`:`Showing ${shown} trusted teacher${shown===1?"":"s"}.`;document.getElementById("emptyState").style.display=shown?"none":"block"}
    function hasJoinedDarsi(){try{return localStorage.getItem("darsi_joined")==="1"}catch(e){return false}}
    function isAdmin(){try{return localStorage.getItem("darsi_is_admin")==="1"}catch(e){return false}}
    function isPreviewingAsVisitor(){try{return localStorage.getItem("darsi_admin_preview")==="visitor"}catch(e){return false}}
    function adminBypassActive(){return isAdmin()&&!isPreviewingAsVisitor()}
    function toggleAdminPreview(){try{if(isPreviewingAsVisitor()){localStorage.removeItem("darsi_admin_preview")}else{localStorage.setItem("darsi_admin_preview","visitor");localStorage.removeItem("darsi_joined");localStorage.removeItem("darsi_plan");localStorage.removeItem("darsi_role");localStorage.removeItem("darsi_active_chat")}}catch(e){}location.reload()}
    function renderAdminBanner(){const banner=document.getElementById("adminBanner");if(!banner)return;if(!isAdmin()){banner.classList.remove("show");return}banner.classList.add("show");const previewing=isPreviewingAsVisitor();document.getElementById("adminBannerText").textContent=previewing?t("👁️ Previewing as a normal visitor.","👁️ بتعاين الموقع كزائر عادي."):t("🛡️ Admin mode — everything unlocked.","🛡️ وضع الأدمن — كل حاجة متاحة.");document.getElementById("adminBannerToggle").textContent=previewing?t("Back to admin →","الرجوع للأدمن ←"):t("Preview as visitor →","عاين كزائر ←")}
    function markJoinedDarsi(){try{localStorage.setItem("darsi_joined","1")}catch(e){}}
    function getCurrentPlan(){try{return localStorage.getItem("darsi_plan")||"free"}catch(e){return "free"}}
    function setCurrentPlan(plan){try{localStorage.setItem("darsi_plan",plan)}catch(e){}}
    function getCurrentRole(){try{return localStorage.getItem("darsi_role")||"student"}catch(e){return "student"}}
    function setCurrentRole(role){try{localStorage.setItem("darsi_role",role)}catch(e){}}
    function getActiveChatId(){try{return localStorage.getItem("darsi_active_chat")||""}catch(e){return ""}}
    function setActiveChatId(id){try{localStorage.setItem("darsi_active_chat",id)}catch(e){}}
    function openUpgrade(){const role=getCurrentRole();openJoin(role,role==="teacher"?"pro":"plus")}
    function updatePaymentBox(role){const planSel=document.getElementById(role==="teacher"?"teacherPlan":"studentPlan");if(!planSel)return;const isPaid=planSel.value==="plus"||planSel.value==="pro";const box=document.getElementById(role==="teacher"?"teacherPaymentBox":"studentPaymentBox");const checkbox=document.getElementById(role==="teacher"?"teacherPaymentConfirm":"studentPaymentConfirm");if(box)box.style.display=isPaid?"block":"none";if(checkbox)checkbox.required=isPaid}
    function initPaymentBoxes(){if(typeof WALLET_INFO==="undefined")return;Array.from(document.querySelectorAll(".wallet-method")).forEach(el=>el.textContent=t(WALLET_INFO.method,WALLET_INFO.methodAr));Array.from(document.querySelectorAll(".wallet-number")).forEach(el=>el.textContent=WALLET_INFO.number)}
    function logLocalSubmission(entry){try{const list=JSON.parse(localStorage.getItem("darsi_submissions")||"[]");list.unshift(entry);localStorage.setItem("darsi_submissions",JSON.stringify(list.slice(0,50)))}catch(e){}}
    function sendJoinEmail(data){if(typeof WEB3FORMS_ACCESS_KEY==="undefined")return;if(!WEB3FORMS_ACCESS_KEY||WEB3FORMS_ACCESS_KEY.indexOf("PASTE_YOUR")===0)return;fetch("https://api.web3forms.com/submit",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(Object.assign({access_key:WEB3FORMS_ACCESS_KEY},data))}).catch(()=>{})}
    function unlockDirectory(){const gate=document.getElementById("directoryGate"),content=document.getElementById("directoryContent");if(gate)gate.style.display="none";if(content)content.style.display="block";renderAccountStrip();renderProgressPanel()}
    function renderAccountStrip(){const strip=document.getElementById("accountStrip");if(!strip)return;const planValue=getCurrentPlan();const role=getCurrentRole();const label=planLabels[planValue]||planLabels[role==="teacher"?"basic":"free"];const isPaid=planValue==="plus"||planValue==="pro";document.getElementById("planBadge").textContent=(isPaid?"⭐ ":"")+t(label.en,label.ar);const upgradeBtn=document.getElementById("upgradeBtn");upgradeBtn.style.display=isPaid?"none":"inline-block"}
    function renderProgressPanel(){const panel=document.getElementById("progressPanel");if(!panel)return;if(!adminBypassActive()&&getCurrentRole()==="teacher"){panel.style.display="none";return}panel.style.display="block";if(adminBypassActive()||getCurrentPlan()==="plus"){panel.innerHTML=`<div class="progress-card"><h4>${t("Weekly progress notes","ملاحظات التقدم الأسبوعية")}</h4><p>${t("No notes yet — once your teacher sends a lesson update, it will show up here.","لا توجد ملاحظات بعد — بمجرد أن يرسل مدرسك تحديثًا عن الدرس، هيظهر هنا.")}</p></div>`}else{panel.innerHTML=`<div class="progress-card locked"><h4>🔒 ${t("Weekly progress notes","ملاحظات التقدم الأسبوعية")}</h4><p>${t("Available on Student Plus — see exactly what your child is learning every week.","متاحة مع خطة طالب بلس — شوف بالظبط ابنك بيتعلم إيه كل أسبوع.")}</p><button class="secondary" onclick="openUpgrade()">${t("Upgrade to Plus →","الترقية إلى بلس ←")}</button></div>`}}
    function goToTeachers(){if(!hasJoinedDarsi()&&!adminBypassActive()){openJoin("student");return}document.getElementById("teachers").scrollIntoView({behavior:"smooth"})}
    function searchTeachers(event){event.preventDefault();if(!hasJoinedDarsi()&&!adminBypassActive()){openJoin("student");return}const value=document.getElementById("searchSubject").value.toLowerCase();const rules=[["Arabic",["arabic","عربي"]],["French",["french","فرنس"]],["English",["english","ielts","إنجلي"]],["Physics",["physics","فيزي"]],["Chemistry",["chem","كيمي"]],["Biology",["biology","احياء","أحياء"]],["History",["history","تاريخ"]],["Geography",["geography","جغرافيا"]],["Math",["math","رياض"]],["Science",["science","علوم"]]];let wanted="all";for(const [subject,keywords] of rules){if(keywords.some(keyword=>value.includes(keyword))){wanted=subject;break}}const button=document.querySelector(`.filter[data-subject="${wanted}"]`);filterTeachers(button);document.getElementById("teachers").scrollIntoView({behavior:"smooth"})}
    function openChat(id){if(!adminBypassActive()&&getCurrentRole()==="student"&&getCurrentPlan()==="free"){const active=getActiveChatId();if(active&&active!==id){closeProfile();showToast(t("Free plan is limited to 1 active chat — upgrade to Student Plus for unlimited chats.","الخطة المجانية محدودة بمحادثة واحدة نشطة — رقّي إلى طالب بلس عشان محادثات غير محدودة."));setTimeout(openUpgrade,600);return}setActiveChatId(id)}selectedTeacher=id;closeProfile();const profile=teacherProfiles[id];document.getElementById("chatAvatar").className=`avatar ${profile.color}`;document.getElementById("chatAvatar").textContent=profile.initials;document.getElementById("chatName").textContent=profile.name;document.getElementById("messageInput").placeholder=isArabic()?"اكتب رسالة…":"Write a message…";document.getElementById("chatDrawer").classList.add("open");renderMessages();setTimeout(()=>document.getElementById("messageInput").focus(),150)}
    function closeChat(){document.getElementById("chatDrawer").classList.remove("open")}
    function openLastChat(){if(selectedTeacher){openChat(selectedTeacher);return}const hint=document.getElementById("hint");hint.textContent=isArabic()?"اختر زر «راسل المدرس» لبدء محادثة خاصة.":"Choose a teacher’s “Message” button to start a private chat.";hint.classList.add("show");clearTimeout(hintTimer);hintTimer=setTimeout(()=>hint.classList.remove("show"),3000)}
    function renderMessages(){const root=document.getElementById("messages");root.innerHTML="";const messages=chats[selectedTeacher]||[];messages.forEach(message=>{const bubble=document.createElement("div");bubble.className=`bubble ${message.from}`;const text=document.createElement("div");text.textContent=message.text;const time=document.createElement("time");time.textContent=message.time;bubble.appendChild(text);bubble.appendChild(time);root.appendChild(bubble)});root.scrollTop=root.scrollHeight}
    function sendMessage(event){event.preventDefault();const input=document.getElementById("messageInput"),text=input.value.trim();if(!text||!selectedTeacher)return;const recipient=selectedTeacher;const time=new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});if(!chats[recipient])chats[recipient]=[];chats[recipient].push({from:"student",text,time});input.value="";renderMessages();setTimeout(()=>{chats[recipient].push({from:"teacher",text:"Thanks for your message. I'll reply with the best next step shortly.",time:"now"});if(selectedTeacher===recipient)renderMessages()},700)}
    function t(en,ar){return isArabic()?ar:en}
    function toggleMobileMenu(){const menu=document.getElementById("mobileMenu"),toggle=document.getElementById("menuToggle");const open=menu.classList.toggle("open");toggle.classList.toggle("open",open);toggle.setAttribute("aria-expanded",open)}
    function closeMobileMenu(){document.getElementById("mobileMenu").classList.remove("open");const toggle=document.getElementById("menuToggle");toggle.classList.remove("open");toggle.setAttribute("aria-expanded","false")}
    function showToast(message){const container=document.getElementById("toastContainer");const toast=document.createElement("div");toast.className="toast";toast.setAttribute("role","status");toast.textContent=message;container.appendChild(toast);setTimeout(()=>toast.remove(),3000)}
    const planLabels={free:{en:"Free plan",ar:"الخطة المجانية"},plus:{en:"Student Plus",ar:"طالب بلس"},basic:{en:"Basic listing",ar:"الإدراج الأساسي"},pro:{en:"Teacher Pro",ar:"مدرس برو"}};
    function openJoin(role,plan){const overlay=document.getElementById("joinOverlay");overlay.classList.add("open");document.body.style.overflow="hidden";document.getElementById("joinSuccess").style.display="none";document.getElementById("studentForm").style.display=role==="teacher"?"none":"block";document.getElementById("teacherForm").style.display=role==="teacher"?"block":"none";document.getElementById("tabStudent").classList.toggle("active",role!=="teacher");document.getElementById("tabTeacher").classList.toggle("active",role==="teacher");document.querySelector(".modal").setAttribute("aria-labelledby",role==="teacher"?"teacherTitle":"joinTitle");if(plan){const select=document.getElementById(role==="teacher"?"teacherPlan":"studentPlan");if(select)select.value=plan}updatePaymentBox("student");updatePaymentBox("teacher");setTimeout(()=>{const field=document.getElementById(role==="teacher"?"teacherName":"studentName");if(field)field.focus()},200)}
    function closeJoin(){document.getElementById("joinOverlay").classList.remove("open");document.body.style.overflow=""}
    function switchJoinTab(tab){document.getElementById("tabStudent").classList.toggle("active",tab==="student");document.getElementById("tabTeacher").classList.toggle("active",tab==="teacher");document.getElementById("studentForm").style.display=tab==="teacher"?"none":"block";document.getElementById("teacherForm").style.display=tab==="teacher"?"block":"none";document.getElementById("joinSuccess").style.display="none";document.querySelector(".modal").setAttribute("aria-labelledby",tab==="teacher"?"teacherTitle":"joinTitle")}
    function submitJoin(event,role){event.preventDefault();const name=document.getElementById(role==="teacher"?"teacherName":"studentName").value.trim()||t("there","بك");const email=document.getElementById(role==="teacher"?"teacherEmail":"studentEmail").value.trim();const phone=document.getElementById(role==="teacher"?"teacherPhone":"studentPhone").value.trim();const planValue=document.getElementById(role==="teacher"?"teacherPlan":"studentPlan").value;const plan=planLabels[planValue]||planLabels[role==="teacher"?"basic":"free"];const isPaid=planValue==="plus"||planValue==="pro";const paymentConfirmed=isPaid?document.getElementById(role==="teacher"?"teacherPaymentConfirm":"studentPaymentConfirm").checked:false;document.getElementById(role==="teacher"?"teacherForm":"studentForm").style.display="none";document.getElementById("joinSuccess").style.display="block";document.getElementById("successText").textContent=isPaid?t(`Thanks ${name}! We'll confirm your ${plan.en} payment and activate your account within one business day.`,`شكرًا ${name}! هنأكد استلام دفعتك لخطة ${plan.ar} ونفعّل حسابك خلال يوم عمل واحد.`):t(`Thanks ${name}! We'll email you within one business day to confirm your ${plan.en} request.`,`شكرًا ${name}! سنرسل لك بريدًا إلكترونيًا خلال يوم عمل واحد لتأكيد طلب ${plan.ar}.`);showToast(t("Request sent — check your email soon.","تم إرسال الطلب — تحقق من بريدك قريبًا."));markJoinedDarsi();setCurrentRole(role);setCurrentPlan(planValue);unlockDirectory();const entry={name,email,phone,role,plan:plan.en,paid:isPaid,paymentConfirmed,time:new Date().toISOString()};logLocalSubmission(entry);sendJoinEmail({subject:`New Darsi ${role} request — ${name} (${plan.en})`,name,email,phone,role,plan:plan.en,payment_status:isPaid?(paymentConfirmed?"Marked as paid — please verify in your wallet":"Not confirmed"):"Free plan — no payment needed"})}
    function submitNewsletter(event){event.preventDefault();const input=document.getElementById("newsletterEmail");if(!input.value.trim())return;showToast(t("Thanks — check your inbox for a confirmation email.","شكرًا — تحقق من بريدك الإلكتروني لرسالة التأكيد."));input.value=""}
    function toggleSave(button){const saved=button.classList.toggle("saved");button.textContent=saved?"♥":"♡";button.classList.remove("bump");void button.offsetWidth;button.classList.add("bump");showToast(saved?t("Added to your saved teachers.","أُضيف إلى المدرسين المحفوظين لديك."):t("Removed from saved teachers.","أُزيل من المدرسين المحفوظين."))}
    function toggleFaq(button){const item=button.closest(".faq-item");const wasOpen=item.classList.contains("open");Array.from(document.querySelectorAll(".faq-item.open")).forEach(open=>{open.classList.remove("open");open.querySelector(".faq-q").setAttribute("aria-expanded","false")});if(!wasOpen){item.classList.add("open");button.setAttribute("aria-expanded","true")}}
    function togglePlanPeriod(){const switchEl=document.getElementById("planSwitch");const on=switchEl.classList.toggle("on");switchEl.setAttribute("aria-checked",on);document.body.classList.toggle("yearly-active",on)}
    function initScrollEffects(){const header=document.getElementById("siteHeader"),progress=document.getElementById("progressBar"),backToTop=document.getElementById("backToTop");function onScroll(){const y=window.scrollY||document.documentElement.scrollTop;const doc=document.documentElement;const scrollable=doc.scrollHeight-doc.clientHeight;const pct=scrollable>0?(y/scrollable)*100:0;progress.style.width=pct+"%";header.classList.toggle("scrolled",y>10);backToTop.classList.toggle("show",y>480)}window.addEventListener("scroll",onScroll,{passive:true});onScroll()}
    document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeJoin();closeChat();closeMobileMenu()}});
    function activateAnimations(){const nodes=Array.from(document.querySelectorAll(".reveal"));if(!("IntersectionObserver" in window)){nodes.forEach(node=>node.classList.add("visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});nodes.forEach(node=>observer.observe(node))}
    activateAnimations();
    initScrollEffects();
    filterTeachers(document.querySelector(".filter.active"));
    if(hasJoinedDarsi()||adminBypassActive())unlockDirectory();
    initPaymentBoxes();
    renderAdminBanner();
